### ISSUE TITLE
Unknown data type 

### ISSUE THREAD

**Issue by ElectricMaxxx** [Qafoo/ser-pretty#10]
Hi,

There are several serialized objects, which i can't make pretty. I got the following exception:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unknown data type "1" (char "1" (#112), context: …1:{i:0;…)' in phar:///home/maximilian/SerPretty/ser-pretty.phar/src/main/Qafoo/SerPretty/Parser.php:77
Stack trace:
#0 phar:///home/maximilian/SerPretty/ser-pretty.phar/src/main/Qafoo/SerPretty/Parser.php(242): Qafoo\SerPretty\Parser->doParse()
#1 phar:///home/maximilian/SerPretty/ser-pretty.phar/src/main/Qafoo/SerPretty/Parser.php(66): Qafoo\SerPretty\Parser->parseObject()
#2 phar:///home/maximilian/SerPretty/ser-pretty.phar/src/main/Qafoo/SerPretty/Parser.php(45): Qafoo\SerPretty\Parser->doParse()
#3 phar:///home/maximilian/SerPretty/ser-pretty.phar/src/bin/ser-pretty(31): Qafoo\SerPretty\Parser->parse('O:15:"Jira_Api_...')
#4 /home/maximilian/SerPretty/ser-pretty.phar(10): require('phar:///home/ma...')
#5 {main}
  thrown in phar:///home/maximilian/SerPretty/ser-pretty.phar/src/main/Qafoo/SerPretty/Parser.php on line 77
``` 

for the following simple string:
```
O:15:"Jira_Api_Result":5:{s:9:"*expand";N;s:10:"*startAt";N;s:13:"*maxResults";N;s:8:"*total";N;s:9:"*result";a:1:{i:0;a:8:{s:4:"self";s:56:"https://maycrm.atlassian.net/rest/api/2/attachment/10000";s:2:"id";s:5:"10000";s:8:"filename";s:27:"Tests/Fixtures/vcf/test.vcf";s:6:"author";a:8:{s:4:"self";s:73:"https://maycrm.atlassian.net/rest/api/2/user?username=maximilian.berghoff";s:4:"name";s:19:"maximilian.berghoff";s:3:"key";s:19:"maximilian.berghoff";s:12:"emailAddress";s:32:"maximilian.berghoff@mayflower.de";s:10:"avatarUrls";a:4:{s:5:"48x48";s:61:"https://maycrm.atlassian.net/secure/useravatar?avatarId=10102";s:5:"24x24";s:72:"https://maycrm.atlassian.net/secure/useravatar?size=small&avatarId=10102";s:5:"16x16";s:73:"https://maycrm.atlassian.net/secure/useravatar?size=xsmall&avatarId=10102";s:5:"32x32";s:73:"https://maycrm.atlassian.net/secure/useravatar?size=medium&avatarId=10102";}s:11:"displayName";s:19:"Maximilian Berghoff";s:6:"active";b:1;s:8:"timeZone";s:13:"Europe/Berlin";}s:7:"created";s:28:"2015-03-02T10:33:20.035+0100";s:4:"size";i:757;s:8:"mimeType";s:12:"text/x-vcard";s:7:"content";s:86:"https://maycrm.atlassian.net/secure/attachment/10000/Tests%2FFixtures%2Fvcf%2Ftest.vcf";}}}

``` 
(simply serialized from an object in php)

**Comment by tobyS** [comment]
Your serialized code misses all Null bytes, probably due to escaping rules of the webform. Could you provide a download of the captured serialization? Optimally capture that output by piping it to a file on the shell without using an editor to copy/paste the output. Thx!

**Comment by ElectricMaxxx** [comment]
Uh, yea i will do when i have the next example. I think i will bekomme
some of that hardcore debugging sessions by serialize into file in
september or octobre again. :-)
You can keep this open if you can live with that, or close it and i will
re-open when i have the issue again.
